'use strict';

const fs   = require('fs');
const path = require('path');

const TEMPLATE_PATH = path.join(__dirname, 'code.py');

/**
 * generateFirmware(config, mac, serviceUrl)
 *
 * Reads circuitpy/code.py (the authoritative firmware template) and replaces
 * {{TOKEN}} placeholders with device-specific values from Firestore config.
 *
 * Tokens defined in code.py:
 *   {{HEADER}}          — generated device/build info lines
 *   {{SERVER_URL}}      — this server's public URL
 *   {{BRIGHTNESS}}      — float 0.0–1.0
 *   {{SCROLL_SPEED}}    — seconds per view panel (int)
 *   {{STATION_ID}}      — GTFS parent station ID (e.g. "G26")
 *   {{WEATHER_API_KEY}} — OpenWeatherMap API key
 *   {{ZIP_CODE}}        — zip code for weather queries
 */
function generateFirmware(config, mac, serviceUrl) {
  const template = fs.readFileSync(TEMPLATE_PATH, 'utf8');

  const header = [
    'Auto-generated by subway-sign server — do not edit manually.',
    `Device : ${mac}`,
    `Station: ${config.station_id} (${config.display_name})`,
    `Built  : ${new Date().toISOString()}`,
  ].join('\n');

  return template
    .replace('{{HEADER}}',          header)
    .replace('{{SERVER_URL}}',      serviceUrl)
    .replace('{{BRIGHTNESS}}',      config.brightness)
    .replace('{{SCROLL_SPEED}}',    config.scroll_speed)
    .replace('{{STATION_ID}}',      config.station_id)
    .replace('{{WEATHER_API_KEY}}', config.openweather_api_key || '')
    .replace('{{ZIP_CODE}}',        config.zip_code || '');
}

module.exports = generateFirmware;
